/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.diegotomfurtado.unicap.integrationtest;

import org.jdbi.v3.core.Jdbi;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class AppTest {

	private final String INSERT_QUERY = "INSERT INTO bank.BALANCE(user_id, balance) VALUES (?, ?)";

	private final String FERNANDO_USER = "fernando";
	private final String DIEGO_USER = "diego";
	private final Double INITIAL_AMOUNT = 1000.0;

	private Jdbi jdbi;
	private App app;

	@Before
	public void setUp() {
		this.jdbi = JdbiFactory.create();
		this.app = new App(this.jdbi);

		this.jdbi.useHandle(handle -> {
			handle.execute(INSERT_QUERY, FERNANDO_USER, INITIAL_AMOUNT);
			handle.execute(INSERT_QUERY, DIEGO_USER, INITIAL_AMOUNT);
		});
	}

	@After
	public void tearDown() {
		this.jdbi.useHandle(handle -> handle.execute("DELETE FROM bank.BALANCE"));
	}

	@Test
	public void testTransfer() {
		
		this.app.transfer(FERNANDO_USER, DIEGO_USER, INITIAL_AMOUNT.intValue());
		
		Double finalAmount = 
				this.jdbi.withHandle(
						handle -> handle
						.select("select balance from bank.balance where user_id = ?", DIEGO_USER)
						.mapTo(Double.class)
						.first()
				);
		Assert.assertEquals(INITIAL_AMOUNT * 2, finalAmount, 0.0);
		
	}
}
